abstract class CssStyleDeclaration2 {
  String? get css_margin; //
  String? get css_maxHeight; //
  String? get css_maxWidth; //
  String? get css_minHeight; //
  String? get css_minWidth; //
  String? get css_display; //
  String? get css_backgroundColor; //
  String? get css_backgroundImage; //
  String? get css_backgroundPosition; //
  String? get css_backgroundSize; //
  String? get css_borderTopLeftRadius; //
  String? get css_borderTopRightRadius; //
  String? get css_borderBottomLeftRadius; //
  String? get css_borderBottomRightRadius; //
  String? get css_boxShadow; //
  String? get css_flexDirection; //
  String? get css_justifyContent; //
  String? get css_alignItems; //
  String? get css_flexGrow; //
  String? get css_flexShrink; //
  String? get css_flexBasis; //
  String? get css_objectFit; //
  String? get css_width; //
  String? get css_height; //
  String? get css_textAlign; //
  String? get css_lineHeight; //
  String? get css_fontSize; //
  String? get css_color; //
  String? get css_fontWeight; //
  String? get css_fontFamily; //
}
