name: alfred

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  html: ^0.15.0 # TODO remove this dependency
  mime: ^1.0.0 # TODO remove this dependency
  mime_type: ^1.0.0 # TODO remove this dependency
  queue: ^3.1.0 # TODO remove this dependency

dev_dependencies:
  extra_pedantic: 1.5.0
  http: ^0.13.2
  logging: ^1.0.1
  test: ^1.14.4
  web_socket_channel: ^2.0.0
