name: alfred

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  html: ^0.15.0 # TODO remove this dependency
  mime: ^1.0.0 # TODO remove this dependency
  queue: ^3.1.0 # TODO remove this dependency

dev_dependencies:
  build_runner: ">=1.6.2 <3.0.0"
  build_web_compilers: ^3.2.2
  extra_pedantic: 4.0.0
  http: ^0.13.4
  logging: ^1.0.2
  test: ^1.20.1
  web_socket_channel: ^2.1.0
  webdev:
