name: polyonal_map_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none

dependencies:
  intl: any # TODO remove this dependency
  plotter_dart:
    path: ../plotter

dev_dependencies:
  build_runner: ">=1.6.2 <3.0.0"
  build_web_compilers: ^2.11.0
  extra_pedantic: ^1.5.0
  test: ^1.17.10
